server:
  port: 8081

spring:
  application:
    name: client-service
  datasource:
    url: jdbc:h2:mem:ms-client-db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console